export const USER_SIGNIN_REQUEST = 'USER_SIGN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGN_FAIL';
export const USER_REGISTER_REQUEST = 'USER_SIGN_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_SIGN_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_SIGN_FAIL';
