const text =
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco';

const data = {
  products: [
    {
      _id: 1,
      name: 'ACID Blondie',
      category: 'cigars',
      image: '/images/acid-blondie_6.png',
      brand: 'ACID Cigars',
      price: 20,
      rank: 1,
      description: text,
      stock: 10,
    },
    {
      _id: 2,
      name: 'Alec Bradley Seconds',
      category: 'cigars',
      image: '/images/alec-bradley.png',
      brand: 'Alec Bradley Cigars',
      price: 30,
      rank: 2,
      description: text,
      stock: 10,
    },
    {
      _id: 3,
      name: 'ACID Buba Kuba',
      category: 'cigars',
      image: '/images/acid-buba.png',
      brand: 'ACID Cigars',
      price: 15,
      rank: 3,
      description: text,
      stock: 10,
    },
    {
      _id: 4,
      name: 'ACID Ripcord',
      category: 'cigars',
      image: '/images/acid-rip-cord.png',
      brand: 'ACID Cigars',
      price: 50,
      rank: 4,
      description: text,
      stock: 10,
    },
    {
      _id: 5,
      name: 'Vertigo Black Lighter',
      category: 'lighters',
      image: '/images/vertigo.jpeg',
      brand: 'Vertigo',
      price: 10,
      rank: 5,
      description: text,
      stock: 10,
    },
    {
      _id: 6,
      name: 'Vertigo Silver Lighter',
      category: 'lighters',
      image: '/images/silver-vertigo.png',
      brand: 'Vertigo',
      price: 20,
      rank: 6,
      description: text,
      stock: 10,
    },
    {
      _id: 7,
      name: 'Single Jet Burgundy',
      category: 'lighters',
      image: '/images/bl-singlejet.jpeg',
      brand: 'Black Label',
      price: 15,
      rank: 7,
      description: text,
      stock: 10,
    },
    {
      _id: 8,
      name: 'CT Filler',
      category: 'wrappers',
      image: '/images/ct-wrapper.jpg',
      brand: 'CT Leaves',
      price: 17,
      rank: 8,
      description: text,
      stock: 10,
    },
    {
      _id: 9,
      name: 'LL Filler',
      category: 'wrappers',
      image: '/images/ll-spread.jpg',
      brand: 'LL Leaves',
      price: 23,
      rank: 9,
      description: text,
      stock: 10,
    },
    {
      _id: 10,
      name: 'VA Brightleaf',
      category: 'wrappers',
      image: '/images/va-brightleaf.jpg',
      brand: 'VA Leaves',
      price: 19,
      rank: 10,
      description: text,
      stock: 10,
    },
  ],
};

module.exports = data;
